defaults: &defaults

development:
  <<: *defaults
  domain: http://0.0.0.0:3000

test:
  <<: *defaults
  domain: http://0.0.0.0:3000

production:
  <<: *defaults
  domain: http://qiang-skills.herokuapp.com