defaults: &defaults
  smtp_address: smtp.mandrillapp.com

development:
  <<: *defaults
  host: nitrousbox.com
  domain: nitrousbox.com
  subdomain: supersonic-dragonstone-28-163715.apne1

test:
  <<: *defaults
  host: nitrousbox.com
  domain: nitrousbox.com
  subdomain: supersonic-dragonstone-28-163715.apne1

production:
  <<: *defaults
  host: herokuapp.com
  domain: herokuapp.com
  subdomain: qiang-skills